AWSTemplateFormatVersion: '2010-09-09'
Transform: "AWS::Serverless-2016-10-31"
Description: "Vault app API"

Globals:
  Function:
    Timeout: 5

Parameters:
  DbHost:
    Type: String
    Description: "Postgres host URL"
  DbPassword:
    Type: String
    Description: "Postgres database password"
    NoEcho: true
  DbUser:
    Type: String
    Description: "Postgres database user"
    NoEcho: true

Resources:
  VaultApiFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      CodeUri: ../api/ # where Makefile is
      Description: "Part of Vault: API app in Go"
      Runtime: provided.al2023
      Handler: bootstrap
      Architectures:
        - x86_64
      Environment:
        Variables:
          AUTH_TOKEN_LIFESPAN: 10080
          DB_HOST: !Ref DbHost
          DB_NAME: vault
          DB_USER: !Ref DbUser
          DB_PASSWORD: !Ref DbPassword
          DB_PORT: 5432
          GIN_MODE: release
          JWT_SECRET: 1
          MODE: "lambda"
      FunctionName: "vault-api"
      Policies:
        - AWSLambdaBasicExecutionRole

  VaultApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: vault-api
      Description: "Vault REST API"
      EndpointConfiguration:
        Types:
          - REGIONAL

  VaultApiRootResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref VaultApi
      ParentId: !GetAtt VaultApi.RootResourceId
      PathPart: "{proxy+}"

  VaultApiMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref VaultApi
      ResourceId: !Ref VaultApiRootResource
      HttpMethod: ANY
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri:
          Fn::Sub: >-
            arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${VaultApiFunction.Arn}/invocations

  VaultApiDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn: VaultApiMethod
    Properties:
      RestApiId: !Ref VaultApi

  VaultApiStage:
    Type: AWS::ApiGateway::Stage
    Properties:
      RestApiId: !Ref VaultApi
      DeploymentId: !Ref VaultApiDeployment
      StageName: v1
      Description: "v1 stage"

  VaultApiPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref VaultApiFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${VaultApi}/*/*/*"

Outputs:
  VaultApiUrl:
    Description: "Invoke URL of the Vault API"
    Value: !Sub "https://${VaultApi}.execute-api.${AWS::Region}.amazonaws.com/${VaultApiStage}/"
    Export:
      Name: VaultApiUrl
