version = 0.1
[dev]
[dev.deploy]
[dev.deploy.parameters]
stack_name = "vault-web"
s3_bucket = "583168578067-sam"
s3_prefix = "vault-web"
region = "ca-central-1"
profile = "personal"
confirm_changeset = true
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM"
parameter_overrides = """
    Environment=\"dev\"
"""
image_repositories = []